name: Terraform Deployment

on:
  workflow_dispatch:
  push:
    paths:
      - 'Terraform/**'  # Trigger workflow on push to changes in 'terraform/' directory
  pull_request:
    paths:
      - 'Terraform/**'  # Trigger workflow on pull request changes in 'terraform/' directory

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0  # Replace with your Terraform version

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          mkdir ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
          aws configure set default.region us-east-1  # Adjust region as needed

      - name: Terraform Init
        working-directory: Terraform/
        run: terraform init

      - name: Terraform Validate
        working-directory: Terraform/
        run: terraform validate

      - name: Create terraform.tfvars
        run: |
          echo "ENV = \"${{ secrets.ENV }}\"" >> terraform.tfvars
          echo "VPC_CIDR = \"${{ secrets.VPC_CIDR }}\"" >> terraform.tfvars

      - name: Terraform Plan
        working-directory: Terraform/
        run: terraform plan -var-file=terraform.tfvars

      - name: Terraform Apply
        working-directory: Terraform/
        run: terraform apply -auto-approve -var-file=terraform.tfvars